#!/bin/zsh
set -eu

ROOT=${0:A:h:h}
: ${TODO_LISTS_DIR:?TODO_LISTS_DIR must be configured by the scheduler}
TODAY=${TODO_DATE:-$(date +%F)}
YESTERDAY=$(date -j -f %Y-%m-%d -v-1d "$TODAY" +%F)
DAY_DIR="$TODO_LISTS_DIR/$TODAY"
PREVIOUS="$TODO_LISTS_DIR/$YESTERDAY/todo.json"
arguments=(list create --date "$TODAY" --output "$DAY_DIR/todo.json")
[[ -f "$PREVIOUS" ]] && arguments+=(--previous "$PREVIOUS")
"$ROOT/bin/todo" $arguments
"$ROOT/bin/todo" view render "$DAY_DIR/todo.json" --output-dir "$DAY_DIR"
